### ---- BOOK ----
# DEVUELVE los datos de las reservas
GET http://localhost:3000/api/book/2020-12-03

###
# DEVUELVE los datos de una reserva por id para el editForm
GET http://localhost:3000/api/book/edit/1

###

# RECOGE los datos de la reserva editada 
# PUT http://localhost:3000/api/book/edit/editada
# Content-Type: application/json


#    {
#      "nombre": "prueba000",
#      "apellidos": "apellidos17",
#      "telefono": 688888880,
#      "email": "email@gmail.com",
#      "fecha": "2020-12-27",
#      "hora": "14:00",
#      "mesas": [
#          {"numero": 3} 
#      ],
#      "personas": 6,
#      "nota": "Estoy del PUT hasta la PO"
#  }


###

# RECOGE los datos del cliente actualizado !!!!!!!!
PUT http://localhost:3000/api/book/edit/cliente
Content-Type: application/json

{
    "idReserva":1,
     "nombre": "Alex",
     "apellidos": "Rubio",
     "telefono": 222044997,
     "email": "alex@mail.com",
     "fecha": "2020-12-22",
     "hora": "15:35",
     "mesas": [
         {"numero": 2}
     ],
     "personas": 4,
     "nota": "Alex dice que quiere bla bla bla"
 }



### ---- RESERVE ----
# DEVUELVE las mesas con reserva en una fecha y una hora
POST http://localhost:3000/api/reserve
Content-Type: application/json

{
    "fecha": "2020-11-30",
    "hora": "21:00:00"
}

###
# RECOGE e inserta los datos de una reserva
POST http://localhost:3000/api/reserve/nueva
Content-Type: application/json

 {
     "nombre": "Alberto",
     "apellidos": "Chicote",
     "telefono": 640922222,
     "email": "alberto@mail.com",
     "fecha": "2020-12-22",
     "hora": "14:00",
     "mesas": [
         {"numero": 3}
     ],
     "personas": 6,
     "nota": "Guarro!!!"
 }






